apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app
    version: blue # This can be changed to "green" when switching traffic
